    <?php if($this->isLoggedIn){ ?>
    <form action="/sticker/id/<?php echo $this->sticker["id"]; ?>" method="post"/> 
        <input type="hidden" name="id" value="<?php echo $this->sticker["id"]; ?>" />
        <?php } ?>
<h2 class="sticker-title">
    <?php echo $this->sticker["title"]; ?>
    <?php if($this->isLoggedIn){ ?>
        <button type="submit"><i class="fa fa-star<?php if(!$this->favorite){ echo "-o"; } ?>" aria-hidden="true"></i></button>
    </form>
    <small><a href="/edit/sticker/id/<?php echo $this->sticker["id"]; ?>">Editer</a></small>

<?php } ?>
</h2>

<div class="sticker-categories">

<?php foreach($this->categories as $cat) { ?>
    <a href="/search?q=<?php echo $cat["name"]; ?>">#<?php echo $cat["name"]; ?></a>&nbsp;
<?php } ?>
</div>
<h3>Prises de vue</h3>
<div class="row pictures">
<?php if($this->pictures) { ?>
    <div class="col-8 showed-picture-caption">
            <div class="col-12 showed-picture-content">
                <a id="showed-link" href="/"><img id="showed-picture" src="" alt=""></a>
            </div>
            <div id="showed-picture-description" class="col-12 showed-picture-description">
                
                 
            </div>
        </div>
        <ul id="listed-pictures" class="col-4 list-pictures">
            <?php 
                $type   =   array(1 => "main", 2 => "common", 3 => "printable");
                foreach($this->pictures as $picture)  { 
            ?>
                <li class="available-img">
                    <img class="sticker-picture-<?php echo $type[$picture["type"]]; ?>" src="/picture/<?php echo $picture["name"] ?>" alt=""/>
                        <p class="list-picture-legend"><?php echo $picture["legende"]; ?></p>
                        <?php if($this->isLoggedIn){ ?>
                            <small><a href="/edit/sticker/id/<?php echo $this->sticker["id"]; ?>#edit-legende-<?php echo $picture["legende_id"]; ?>">Editer</a></small>
                        <?php } ?>
                </li>
            <?php } ?>
        </ul>
    <?php } else { ?>
        <small>Aucune photo à afficher... </small>
        <?php if($this->isLoggedIn){ ?>
            <small><a href="/edit/sticker/id/<?php echo $this->sticker["id"]; ?>#add-picture">Ajouter des photos</a></small>
    <?php }
    } ?>

</div>


<div class="row sticker-information">
    <h3>
        Informations sur le sticker <?php if($this->isLoggedIn){ ?><small><a href="/edit/sticker/id/<?php echo $this->sticker["id"]; ?>#edit-infos">Editer</a></small> <?php } ?>
    </h3>
    <?php 
        if($this->infos && trim($this->infos["content"])){ 
            echo "<p>" . $this->infos["content"] . "</p>"; 
        } else { ?>
        <small>Aucune information n'existe pour ce sticker...</small>
    <?php } ?>
    <br/>
    <br/>
</div>

