<h2>Administration des photos</h2>

<?php 
if(count($this->listes)) { 
    $title  =   array(
        "validated" =>  "Validés",
        "refused"   =>  "Refusés",
        "waiting"   =>  "En attente de validation"
    );
    foreach($this->listes as $level =>  $liste){
?>
<h3><?php echo $title[$level]; ?></h3>
<table>
    <thead>
        <tr>
            <td>Numéro/lien</td>  
            <td>Sticker</td>
            <td>Date de création</td>
            <td>Auteur</td>
            <td>Mail</td>
            <td>Action</td>
            <td>Supprimer</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($liste as $picture) { ?>
        <form action="/back/admin/liste/pictures" method="post">
            <tr>
                <td><a href="/picture/<?php echo $picture["name"]; ?>">#<?php echo $picture["id"]; ?></a></td>
                <td><a href="/sticker/id/<?php echo $picture["id_sticker"] ?>"><?php echo $picture["name_sticker"]; ?></a></td>
                <td><?php echo $picture["creation"]; ?></td>
                <td><?php echo $picture["pseudo_author"]; ?></td>
                <td><?php echo $picture["mail_author"]; ?></td>
                <td>
                    <?php if($level != "validated") { ?><input name="validation" type="radio" value="validate"/> Valider</br><?php } ?>
                    <?php if($level != "refused") { ?><input name="validation" type="radio" value="refuse"/>Refuser<?php } ?>
                <td><input name="delete" type="checkbox" value="delete"/></td>
                <td>
                    <input name="id" type="hidden" value="<?php echo $picture["id"]; ?>"/>
                    <input type="submit" value="Mettre à jour"/>
                </td>
            </tr>
        </form>
        <?php } ?>
    </tbody>
</table>

<?php } 
} else { ?>

<small>Aucun contenu à afficher</small>

<?php }?>

