<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Bibliastick</title>
        <link rel="icon" type="image/png" href="/assets/img/logo_64.png"/>
        <link rel="stylesheet" href="/assets/css/font-awesome.css"/>
        <link rel="stylesheet" href="/assets/css/grid.css"/>
        <link rel="stylesheet" href="/assets/css/style.css"/>
    </head>
    <body>
         <h1 class="title"><a href="/"><img src="/assets/img/logo_32.png" alt="logo"/> Biblia<span class="title-bold">stick</span></a></h1>

        <h1>Login</h1>
        <?php 
            if(count($this->_errors)){
        ?>
        <div id="liste-errors">
            <?php foreach($this->_errors as $level => $group) { ?>
            <ul id="list-errors-l<?php echo $level; ?>">
                <?php foreach($group as $error) { ?>
                    <li><?php echo $error; ?></li>
                <?php } ?>
            </ul>
            <?php }?>
        </div>
        <?php 
            }
            if(count($this->_messages)){
        ?>
        <div id="liste-messages">
            <ul>
                <?php foreach($this->_messages as $message) { ?>
                    <li><?php echo $message; ?></li>
                <?php } ?>
            </ul>
        </div>
        <?php } ?>
        <form method="post" action="/back/login">
            <label for="pseudo">Pseudo</label>
            <input name="pseudo"/>
            <br/>
            <label for="pass">Mot de passe</label>
            <input name="pass" type="password"/>
            <br/>
            <input type="submit" value="connection"/>
        </form>
    </body>
</html>
