<h1>Bibliastick : login</h1>
<?php 
    if(count($this->_errors)){
?>
<div id="liste-errors">
    <?php foreach($this->_errors as $level => $group) { ?>
    <ul id="list-errors-l<?php echo $level; ?>">
        <?php foreach($group as $error) { ?>
            <li><?php echo $error; ?></li>
        <?php } ?>
    </ul>
    <?php }?>
</div>
<?php 
    }
    if(count($this->_messages)){
?>
<div id="liste-messages">
    <ul>
        <?php foreach($this->_messages as $message) { ?>
            <li><?php echo $message; ?></li>
        <?php } ?>
    </ul>
</div>
<?php } ?>
<form method="post" action="/back/login">
    <label for="pseudo">Pseudo</label>
    <input name="pseudo"/>
    <br/>
    <label for="pass">Mot de passe</label>
    <input name="pass" type="password"/>
    <br/>
    <input type="submit" value="connection"/>
</form>
