<h2>Administration des contributions</h2>

<?php if(count($this->listeContrib)) { 
    $titles =   array(
        "waiting"   =>  "En attente de validation",
        "refused"   =>  "Refusées",
        "validated" =>  "Validée"
    );
    foreach($this->listeContrib as $level => $contribs) { ?>
    <h3><?php echo $titles[$level]; ?></h3>

    <table>
        <thead>
            <tr>
                <td>Sticker/Picture</td>
                <td>Contenu</td>
                <td>Date et heure</td>
                <td>Auteur</td>
                <td>Mail</td>
                <?php if($level != "refused") { ?><td>Validation</td><?php } ?>
                <td>Supprimer</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($contribs as $contrib) {  ?>
            <form action="/back/admin/liste/contributions" method="post">
                <tr>
                    <td>
                       <?php if($contrib["id_picture"]) { ?>[p] <a href="/picture/<?php echo $contrib["name_picture"] ?>">#<?php echo $contrib["id_picture"] ; ?></a>
                       <?php } if($contrib["id_sticker"]) {  ?>[s] <a href="/sticker/id/<?php echo $contrib["id_sticker"] ?>"><?php echo $contrib["title_sticker"] ?></a></td>
                       <?php } ?>
                    <td><textarea name="content" cols="30" rows="5"><?php echo $contrib["contenu"]; ?></textarea></td>
                    <td><?php echo $contrib["date"];?></td>
                    <td><?php echo $contrib["pseudo_author"];?></td>
                    <td><a href="mailto:<?php echo $contrib["mail_author"];?>"><?php echo $contrib["mail_author"];?></a></td>
                    <?php if($level != "refused") { ?>
                        <td>
                            <?php if($level != "validated") { ?><input name="validation" type="radio" value="validate"/> [V]</br><?php } ?>
                            <?php if($level != "refused") { ?><input name="validation" type="radio" value="refuse"/> [R]<?php } ?>
                        </td>
                    <?php } ?>
                    <td><input name="delete" type="checkbox" value="delete" /></td>
                    <td>
                        <input type="hidden" name="id" value="<?php echo $contrib["id"]; ?>"/>
                        <input type="submit" value="Mettre à jour"/>
                    </td>
                </tr>
            </form>
            <?php } ?>
        
        </tbody>

    </table>


<?php 
    }
} else { 
?>
<small>Aucune contribution à afficher</small>
<?php 
} 
?>
