<h2>Edition d'un sticker</h2>

<div id="add-picture">
    <h3>Photos [edition]</h3>
    <h4>Ajouter</h4>
    <form enctype="multipart/form-data" action="/edit/sticker/id/<?php echo $this->sticker["id"]; ?>" method="post">
        <label for="new_picture_sticker">Choisir un ficher : </label></label><input name="new_picture_sticker" type="file" accept="image/*"/>
        <label for="description">Légende</label><textarea name="description" cols="30" rows="10"></textarea>
        <label for="type">Type</label>
            <select name="type">
                <option value="2" selected>Commune</option>
                <option value="3">Imprimable</option>
            </select>
        <input name="editaction" type="hidden" value="add-picture"/>
        <input type="submit" value="Uploader" />
    </form>
    <?php if(count($this->pictures)) { ?>
    <h4>Editer les légendes</h4>
    <ul>
        <?php foreach($this->pictures as $picture)  { ?>
            <li>
                <img src="/picture/<?php echo $picture["name"] ?>" alt=""/>
            </li>
        <?php } ?>
    </ul>
    <?php } ?>

</div>
<div id="edit-infos">
    <h3>Informations [edition]</h2>

</div>

