<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Bibliastick</title>
        <link rel="icon" type="image/png" href="/assets/img/logo_64.png"/>
        <link rel="stylesheet" href="/assets/css/font-awesome.css"/>
        <link rel="stylesheet" href="/assets/css/grid.css"/>
        <link rel="stylesheet" href="/assets/css/style.css"/>
    </head>
    <body>
        <div class="container home-content">
            <h1 class="title"><a href="/"><img src="/assets/img/logo_64.png" alt="logo"/> Biblia<span class="title-bold">stick</span></a></h1>
            <form class="home-form" action="/search" method="get">
                <div class="home-form-search">
                    <input name="q" placeholder="Type a keyword, a category, etc..."/>
                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
            </form>
        <footer class="container home-footer">
            <div class="row">
                <div class="col-o-3 col-2"><a href="">About</a></div>
                <div class="col-2"><a href="/back/login">Login</a></div>
                <div class="col-2"><a href="">Legal</a></div>
            </div>
        </footer>
        </div>
    </body>
</html>
