<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Bibliastick</title>
        <link rel="icon" type="image/png" href="/assets/img/logo_64.png"/>
        <link rel="stylesheet" href="/assets/css/grid.css"/>
        <link rel="stylesheet" href="/assets/css/style.css"/>
    </head>
    <body>
        <h1>Bibliastick</h1>
        <form action="/search" method="get">
            <input name="q" placeholder="Type a keyword, a category, etc..."/>
            <input type="submit" value"search"/>
        </form>
    </body>
</html>
