<h1>Bibliastick : page d'inscription</h1>

<form method="post" action="/signin">
    <p>
        <label for="pseudo">Pseudo</label>
        <input name="pseudo"/>
        <br/>
        <label for="email">Email</label>
        <input name="email" type="mail">
        <br/>
        <label for="pass">Mot de passe</label>
        <input name="pass" type="password">
        <br/>
        <label for="confirmpass">Confirmation du mot de passe</label>
        <input name="confirmpass" type="password">
        <br/>
        <input type="submit" value="Valider"/>
    </p>
</form>
