<h2>Liste de vos photos</h2>
<?php 
if(count($this->listes)) { 
    $title  =   array(
        "validated" =>  "Validés",
        "refused"   =>  "Refusés",
        "waiting"   =>  "En attente de validation"
    );
    foreach($this->listes as $category =>  $liste){
?>
<h3><?php echo $title[$category]; ?></h3>
<table>
    <thead>
        <tr>
            <td>Numéro/lien</td>  
            <td>Date de création</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($liste as $picture) { ?>
            <tr>
                <td><a href="/picture/<?php echo $picture["name"]; ?>">#<?php echo $picture["id"]; ?></a></td>
                <td><?php echo $picture["creation"]; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php } 
} else { ?>

<small>Aucun contenu à afficher</small>

<?php }?>
