<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Bibliastick</title>
        <link rel="icon" type="image/png" href="/assets/img/logo_64.png">
        <link rel="stylesheet" href="/assets/css/font-awesome.css"/>
        <link rel="stylesheet" href="/assets/css/grid.css"/>
        <link rel="stylesheet" href="/assets/css/style.css"/>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-3">
                    <header>
                        <h2><?php echo ucfirst($this->pseudo); ?></h2>
                    </header>
                        <nav>
                            <div class="tools">
                                <h2>Outils</h2>
                                <h3>Participations</h3>
                                <ul>
                                    <li><a href="/back/liste/stickers">Stickers</a></li>
                                    <li><a href="/back/liste/contributions">Informations</a></li>
                                    <li><a href="/back/liste/pictures">Photos</a></li>
                                    <li><a href="/back/liste/categories">Categories</a></li>
                                </ul>
                                <h3>Autre</h3>
                                <ul>
                                    <li><a href="/back/liste/stickers/mine">Vos stickers</a></li>
                                    <li><a href="/back/messages">Messagerie</a></li>
                                    <li><a href="/back/logout">Déconnexion</a></li>
                                </ul>
                            </div>
                            <?php 
                            if(intval($this->authLevel) >= 2){ ?>
                            <div class="tools tools-admin">
                                <h2>Administration</h2>
                                <h3>Validation</h3>
                                <ul>
                                    <li><a href="/back/admin/liste/stickers">Stickers</a></li>
                                    <li><a href="/back/admin/liste/contributions">Informations</a></li>
                                    <li><a href="/back/admin/liste/pictures">Photos</a></li>
                                    <li><a href="/back/admin/liste/categories">Categories</a></li>
                                </ul>
                                <h3>Autre</h3>
                                <ul>
                                    <li><a href="/back/admin/liste/users">Gestion des utilisateurs</a></li>
                                </ul>
                            </div>
                            <?php } ?>
                        </nav>
                </div>
                <section class="col-9">
                    <?php 
                        if(count($this->_errors)){
                    ?>
                    <div id="liste-errors">
                        <?php foreach($this->_errors as $level => $group) { ?>
                        <ul id="list-errors-l<?php echo $level; ?>">
                            <?php foreach($group as $error) { ?>
                                <li><?php echo $error; ?></li>
                            <?php } ?>
                        </ul>
                        <?php }?>
                    </div>
                    <?php 
                        }
                        if(count($this->_messages)){
                    ?>
                    <div id="liste-messages">
                        <ul>
                            <?php foreach($this->_messages as $message) { ?>
                                <li><?php echo $message; ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                    <?php
                        }
                        $this->render();
                    ?>
                </section>
            </div>
        </div>
    </body>
</html>

