<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bibliastick</title>
    <link rel="icon" type="image/png" href="/assets/img/logo_64.png"/>
</head>
    <body>
        <header>
            <div class="head-caption">
                <img src="/assets/img/logo_64.png" alt="logo" />
                <h1>Bibliastick</h1>
            </div>
            <?php if(isset($this->isLoggedIn) && $this->isLoggedIn) { ?>
            <div>
                <a href="/back/home">Panel</a>
                <a href="/back/logout">Deconnexion</a>
            </div>
            <?php } ?>
            
        </header>
        <div class="container">
            <?php $this->render(); ?>    
        </div>
        <footer>

        </footer>
    </body>
</html>
