<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bibliastick</title>
    <link rel="icon" type="image/png" href="/assets/img/logo_64.png"/>
    <link rel="stylesheet" href="/assets/css/font-awesome.css"/>
    <link rel="stylesheet" href="/assets/css/grid.css"/>
    <link rel="stylesheet" href="/assets/css/style.css"/>
    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/js/lib.js"></script>
</head>
    <body>
        <header class="head-caption">
            <div class="container">
                <h1 class="title"><a href="/"><img src="/assets/img/logo_32.png" alt="logo"/> Biblia<span class="title-bold">stick</span></a></h1>
                <?php if(isset($this->isLoggedIn) && $this->isLoggedIn) { ?>
                <div class="head-caption-actions">
                    <a href="/back/home">Pannel</a>
                </div>
                <?php } ?>
            </div>
        </header>
        <div class="content container">
            <?php $this->render(); ?>    
        </div>
        <footer class="footer-caption container">
            <div class="row">
            <br/>
                <div class="col-o-3 col-2"><a href="">About</a></div>
                <div class="col-2"><a href="/back/login">Login</a></div>
                <div class="col-2"><a href="/signin">Signin</a></div>
            <br/>
            </div>
        </footer>
    </body>
</html>
