<h2>Gestion des catégories</h2>

<div>
    <h3>Créations</h3>
    <?php 
    if(count($this->listes)) { 
        $title  =   array(
            "validated" =>  "Validés",
            "refused"   =>  "Refusés",
            "waiting"   =>  "En attente de validation"
        );
        foreach($this->listes as $level =>  $liste){
    ?>
    <h4><?php echo $title[$level]; ?></h4>
    <table>
        <thead>
            <tr>
                <td>Intitulé</td>
                <td>Parent</td>
                <td>Date de création</td>
                <td>Auteur</td>
                <td>Mail</td>
                <td>Action</td>
                <td>Supprimer</td>
                <td>Action</td>

            </tr>
        </thead>
        <tbody>
            <?php foreach($liste as $category) { ?>
            <form action="/back/admin/liste/categories" method="post">
                <tr>
                    <td><?php echo $category["name"]; ?></td>
                    <td><?php echo $category["parent"]; ?></td>
                    <td><?php echo $category["creation"]; ?></td>
                    <td><?php echo $category["pseudo_author"]; ?></td>
                    <td><?php echo $category["mail_author"]; ?></td>
                    <td>
                        <?php if($level != "validated") { ?><input name="validation" type="radio" value="validate"/> [V]</br><?php } ?>
                        <?php if($level != "refused") { ?><input name="validation" type="radio" value="refuse"/> [R]<?php } ?>
                    <td><input name="delete" type="checkbox" value="delete"/></td>
                    <td>
                        <input name="type" type="hidden" value="creation" />
                        <input name="id" type="hidden" value="<?php echo $category["id"]; ?>"/>
                        <input type="submit" value="Mettre à jour"/>
                    </td>
                </tr>
            </form>
            <?php } ?>
        </tbody>
    </table>

    <?php } 
    } else { ?>

    <small>Aucun contenu à afficher</small>

    <?php }?>
</div>
<div>
    <h3>Affectations</h3>
    <?php 
    if(count($this->affectations)) { 
        $title  =   array(
            "validated" =>  "Validés",
            "refused"   =>  "Refusés",
            "waiting"   =>  "En attente de validation"
        );
        foreach($this->affectations as $level =>  $liste){
    ?>
    <h4><?php echo $title[$level]; ?></h4>
    <table>
        <thead>
            <tr>
                <td>Categorie</td>
                <td>Sticker</td>
                <td>Date de création</td>
                <td>Auteur</td>
                <td>Mail</td>
                <td>Action</td>
                <td>Supprimer</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($liste as $category) { ?>
            <form action="/back/admin/liste/categories" method="post">
                <tr>
                    <td><?php echo $category["name_cat"]; ?></td>
                    <td><a href="/sticker/id/<?php $category["id_sti"]; ?>" /><?php echo $category["title_sti"]; ?></a></td>
                    <td><?php echo $category["creation"]; ?></td>
                    <td><?php echo $category["pseudo_author"]; ?></td>
                    <td><?php echo $category["mail_author"]; ?></td>
                    <td>
                        <?php if($level != "validated") { ?><input name="validation" type="radio" value="validate"/> [V]</br><?php } ?>
                        <?php if($level != "refused") { ?><input name="validation" type="radio" value="refuse"/> [R]<?php } ?>
                    </td>
                    <td><input name="delete" type="checkbox" value="delete"/></td>
                    <td>
                        <input name="id" type="hidden" value="<?php echo $category["id"]; ?>"/>
                        <input name="type" type="hidden" value="affectation" />
                        <input type="submit" value="Mettre à jour"/>
                    </td>
                </tr>
            </form>
            <?php } ?>
        </tbody>
    </table>

    <?php } 
    } else { ?>

    <small>Aucun contenu à afficher</small>

    <?php }?>

    
    

</div>
