<h2>Liste de vos catégories</h2>

<div>
    <h3>Créations</h3>

    <h4>Proposer une nouvelle catégorie</h4>
    <table>
        <thead>
            <tr>
                <td>Intitulé</td>
                <td>Parent</td>
            </tr>
        </thead>
        <tbody>
            <form action="/back/liste/categories" method="post">
                <tr>
                    <td><input name="title" placeholder="Une nouvelle catégorie"/></td>
                    <td>
                       <select name="parent">
                            <option value="0" selected>-- SANS --</option>
                            <?php foreach($this->fulliste as $category) { ?>
                            <option value="<?php echo $category["id"]; ?>"><?php echo $category["name"]; ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    <td>
                        <input type="submit" value="Créer"/>
                    </td>
                </tr>
            </form>
        </tbody>
    </table>

    <?php 
    if(count($this->listes)) { 
        $title  =   array(
            "validated" =>  "Validés",
            "refused"   =>  "Refusés",
            "waiting"   =>  "En attente de validation"
        );
        foreach($this->listes as $level =>  $liste){
    ?>
    <h4><?php echo $title[$level]; ?></h4>
    <table>
        <thead>
            <tr>
                <td>Intitulé</td>
                <td>Parent</td>
                <td>Date de création</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($liste as $category) { ?>
                <tr>
                    <td><?php echo $category["name"]; ?></td>
                    <td><?php echo $category["parent"]; ?></td>
                    <td><?php echo $category["creation"]; ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <?php } 
    } else { ?>

    <small>Aucun contenu à afficher</small>

    <?php }?>
</div>
<div>
    <h3>Affectations</h3>
    <?php 
    if(count($this->affectations)) { 
        $title  =   array(
            "validated" =>  "Validés",
            "refused"   =>  "Refusés",
            "waiting"   =>  "En attente de validation"
        );
        foreach($this->affectations as $level =>  $liste){
    ?>
    <h4><?php echo $title[$level]; ?></h4>
    <table>
        <thead>
            <tr>
                <td>Categorie</td>
                <td>Sticker</td>
                <td>Date de création</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($liste as $category) { ?>
            <form action="/back/admin/liste/categories" method="post">
                <tr>
                    <td><?php echo $category["name_cat"]; ?></td>
                    <td><a href="/sticker/id/<?php $category["id_sti"]; ?>" /><?php echo $category["title_sti"]; ?></a></td>
                    <td><?php echo $category["creation"]; ?></td>
                </tr>
            </form>
            <?php } ?>
        </tbody>
    </table>

    <?php } 
    } else { ?>

    <small>Aucun contenu à afficher</small>

    <?php }?>
</div>
